version: '3.8'

services:
  app:
    container_name: nextjs-app-dev
    build:
      context: .
      target: deps
    command: pnpm dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge